---
title: "sem"
author: "Tom Rupnik MedjedoviÄ"
date: "2024-03-02"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plotly)
```


```{r include=FALSE}
#podatki = read.csv("podatki.csv", sep=';')

podatki = read.csv("podatki.csv", sep=';', na.strings = "...")

# ime stolpca Vzork.smrti --> stevilo
colnames(podatki)[5] = "stevilo"

# ime stolpca Vzrok.smrti.na.1000.prebivalcev --> stevilo1000
colnames(podatki)[6] = "stevilo1000"
```

```{r include=FALSE}
df_mankajoce_vrednosti = podatki[!complete.cases(podatki), ]
df = na.omit(podatki)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
mz = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
mv = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zz = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zv = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]

df = na.omit(data.frame(leto = mz$LETO,
                stevilo.v = c(mv$stevilo,zv$stevilo),
                stevilo.z = c(mz$stevilo, zz$stevilo),
                vzrok = c(mz$VZROK.SMRTI,zz$VZROK.SMRTI),
                spol = c(mz$SPOL, zz$SPOL)))
```

```{r echo=FALSE, fig.height=7, fig.width=11, message=FALSE, warning=FALSE, fig.align="center"}
ui <- fluidPage(
  headerPanel(''),
  sidebarPanel(
    selectInput("izbrano_leto", label="Izberite leto", choices = sort(unique(df$leto)), selected = 2002),
    selectInput("izbran_spol", label="Izberite spol", choices = c("Moski", "Zenske"), selected = "Moski")
    #selected = names(mtcars)[[2]]
    ),
  mainPanel(
    plotlyOutput('plot')
  )
)

server <- function(input, output) {
  
  data <- reactive({

    req(input$izbrano_leto,input$izbran_spol)
    
    df %>% 
      select(leto, stevilo.v, stevilo.z, spol, vzrok) %>%
      filter(leto %in% input$izbrano_leto, spol %in% input$izbran_spol)
  })
  
  output$plot <- renderPlotly(
    plot_ly(marker = list(line = list(color = 'white', width = 1)),) %>%
      add_pie(data = data(), labels = ~vzrok, values = ~stevilo.z,
              name = "Zahodna Slovenija", 
              domain = list(x = c(0, 0.4), y = c(0.1, 0.92))) %>% 
      add_pie(data = data(), labels = ~vzrok, values = ~stevilo.v,
              name = "Vzhodna Slovenija",
              domain = list(x = c(0.58, 0.98), y = c(0.1, 0.92))) %>% 
      layout(title = "", showlegend = T,
             xaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             legend = list(x = 0, y = 0.05, orientation = 'h')) %>%
      add_annotations(x=c(0.082, 0.68), y=1, text = c("Zahodna Slovenija", "Vzhodna Slovenija"), 
                      xref = "paper", yref = "paper", xanchor = "left", showarrow = FALSE)
  )
}

shinyApp(ui,server)
```


