---
title: "Seminarska"
author: "Neža Kržan, Tom Rupnik Medjedovič"
date: "2024-02-27"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages("rjson")
library("rjson")
# library(shiny)
# library(plotly)
# library(dplyr)
# library(tidyverse)
# library(highcharter)
# library(tidyr)
```

```{r include=FALSE}
#podatki = read.csv("podatki.csv", sep=';')

podatki = read.csv("podatki.csv", sep=';', na.strings = "...")

# ime stolpca Vzork.smrti --> stevilo
colnames(podatki)[5] = "stevilo"

# ime stolpca Vzrok.smrti.na.1000.prebivalcev --> stevilo1000
colnames(podatki)[6] = "stevilo1000"

# Vzrok smrti - SKUPAJ --> skupaj
# podatki[podatki$VZROK.SMRTI=="Vzrok smrti - SKUPAJ", "VZROK.SMRTI"] = "skupaj"

# Nekatere infekcijske in parazitske bolezni (A00-B99) --> vzrok1
# podatki[podatki$VZROK.SMRTI=="Nekatere infekcijske in parazitske bolezni (A00-B99)", "VZROK.SMRTI"] = "vzrok1"

# Neoplazme (C00-D48) --> vzrok2
# podatki[podatki$VZROK.SMRTI=="Neoplazme (C00-D48)", "VZROK.SMRTI"] = "vzrok2"

# Bolezni obtocil (I00-I99) --> vzrok3
# podatki[podatki$VZROK.SMRTI=="Bolezni obtocil (I00-I99)", "VZROK.SMRTI"] = "vzrok3"

# Bolezni dihal (J00-J99) --> vzrok4
# podatki[podatki$VZROK.SMRTI=="Bolezni dihal (J00-J99)", "VZROK.SMRTI"] = "vzrok4"

# Bolezni prebavil (K00-K93) --> vzrok5
# podatki[podatki$VZROK.SMRTI=="Bolezni prebavil (K00-K93)", "VZROK.SMRTI"] = "vzrok5"

# Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98) --> vzrok6
# podatki[podatki$VZROK.SMRTI=="Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98)", "VZROK.SMRTI"] = "vzrok6"
```

```{r include=FALSE}
# zapomnimo si indeks vrstic, ki nimajo stevila umrlih
# katere_prazne = NULL
# for(i in 1:nrow(podatki)){
  # if(podatki[i,]$stevilo == "..."){
    # katere_prazne = c(katere_prazne,i)
  # }
# }

# vrstice, ki nimajo podatka(stevila)
# vrstice_brez = podatki[katere_prazne,]

# vrstice, ki imajo podatek(stevilo)
# vrstice_dobre = podatki[-katere_prazne,]
# leto spremenimo iz chr v int
# vrstice_dobre$stevilo = as.integer(vrstice_dobre$stevilo)
# vrstice_dobre$stevilo1000 = as.double(vrstice_dobre$stevilo1000)

df_mankajoce_vrednosti = podatki[!complete.cases(podatki), ]
df = na.omit(podatki)
```


```{r include=FALSE}
# primer iskanja
podatki[c(podatki$VZROK.SMRTI=="skupaj" & podatki$LETO=="2002"),]
```

```{r include=FALSE}
iskanje_vrstic = function(vzrok, regija, spol, leto){
  # iscemo le po "dobrih" vrsticah
  podatki_dobri = vrstice_dobre
  
  rezultat = podatki_dobri[c(podatki_dobri$VZROK.SMRTI %in% vzrok &
                       podatki_dobri$KOHEZIJSKA.REGIJA %in% regija &
                       podatki_dobri$SPOL %in% spol &
                       podatki_dobri$LETO %in% leto),]
  
  rezultat = data.frame(rezultat)
  return(rezultat)
}

#podatki = read.csv("podatki.csv", sep=';', na.strings = "...")

# primer iskanja podatkov
#aa = iskanje_vrstic(c("skupaj", "vzrok1"), "SLOVENIJA", "Spol - SKUPAJ", c(2002:2022))
```




```{r message=FALSE, warning=FALSE, include=FALSE}
mz = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
mv = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zz = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zv = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]

df = na.omit(data.frame(leto = mz$LETO,
                stevilo.v = c(mv$stevilo,zv$stevilo),
                stevilo.z = c(mz$stevilo, zz$stevilo),
                vzrok = c(mz$VZROK.SMRTI,zz$VZROK.SMRTI),
                spol = c(mz$SPOL, zz$SPOL)))
```

```{r echo=FALSE, fig.height=7, fig.width=11, message=FALSE, warning=FALSE, fig.align="center"}
ui <- fluidPage(
  headerPanel(''),
  sidebarPanel(
    selectInput("izbrano_leto", label="Izberite leto", choices = sort(unique(df$leto)), selected = 2002),
    selectInput("izbran_spol", label="Izberite spol", choices = c("Moski", "Zenske"), selected = "Moski")
    #selected = names(mtcars)[[2]]
    ),
  mainPanel(
    plotlyOutput('plot')
  )
)

server <- function(input, output) {
  
  data <- reactive({

    req(input$izbrano_leto,input$izbran_spol)
    
    df %>% 
      select(leto, stevilo.v, stevilo.z, spol, vzrok) %>%
      filter(leto %in% input$izbrano_leto, spol %in% input$izbran_spol)
  })
  
  output$plot <- renderPlotly(
    plot_ly(marker = list(line = list(color = 'white', width = 1)),) %>%
      add_pie(data = data(), labels = ~vzrok, values = ~stevilo.z,
              name = "Zahodna Slovenija", 
              domain = list(x = c(0, 0.4), y = c(0.1, 0.92))) %>% 
      add_pie(data = data(), labels = ~vzrok, values = ~stevilo.v,
              name = "Vzhodna Slovenija",
              domain = list(x = c(0.58, 0.98), y = c(0.1, 0.92))) %>% 
      layout(title = "", showlegend = T,
             xaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             legend = list(x = 0, y = 0.05, orientation = 'h')) %>%
      add_annotations(x=c(0.082, 0.68), y=1, text = c("Zahodna Slovenija", "Vzhodna Slovenija"), 
                      xref = "paper", yref = "paper", xanchor = "left", showarrow = FALSE)
  )
}

shinyApp(ui,server)
```


```{r}
# library(rsconnect)
# rsconnect::deployDoc('Test2.Rmd')
```

